apiVersion: v1
kind: Pod   
metadata:     
  name: go-meter           
spec:
  containers:
  - name: gometer
    image: feixitek/go-meter:v1.0.1
    imagePullPolicy: Always
    command: ["/bin/bash", "-ce", "tail -f /dev/null"]
    volumeDevices:
    - name: datablk
      devicePath: /dev/sde
  volumes:
  - name: datablk
    persistentVolumeClaim:
      claimName: spofblkpvc
