apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc1
  namespace: pvctest
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 11Mi
  storageClassName: linstor
