apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spofpvc
spec:
  storageClassName: linstor3f
  #volumeMode: Block
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
